create table Sensor
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL UNIQUE
);

create table Measurement
(
    id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value            numeric(4, 1) NOT NULL,
    raining          boolean       NOT NULL,
    measurement_time timestamp     NOT NULL,
    sensor_name      varchar REFERENCES Sensor (name) ON DELETE CASCADE
);